---
- name: Converge
  hosts: localhost
  gather_facts: true
  vars:
    dxdfir_memory_memory_dir: /tmp/dxdfir_memory_molecule/mem
    dxdfir_memory_out_dir: /tmp/dxdfir_memory_molecule/out
  tasks:
    - name: "converge | run dxdfir_memory (elastic)"
      ansible.builtin.include_role:
        name: dxdfir_memory
